version: "3"

services: 
    redis-cluster-8006:
        image: redis:5.0.2-alpine
        container_name: node-8006
        ports:
            - "8006:8006"
        network_mode: host
        volumes:
            - ./conf/redis-8006.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-8001:
        image: redis:5.0.2-alpine
        container_name: node-8001
        ports:
            - "8001:8001"
        network_mode: host

        volumes:
            - ./conf/redis-8001.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"
   redis-cluster-8002:
        image: redis:5.0.2-alpine
        container_name: node-8002
        ports:
            - "8002:8002"
        network_mode: host

        volumes:
            - ./conf/redis-8002.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-8003:
        image: redis:5.0.2-alpine
        container_name: node-8003
        ports:
            - "8003:8003"
        network_mode: host

        volumes:
            - ./conf/redis-8003.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-8004:
        image: redis:5.0.2-alpine
        container_name: node-8004
        ports:
            - "8004:8004"
        network_mode: host

        volumes:
            - ./conf/redis-8004.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"

    redis-cluster-8005:
        image: redis:5.0.2-alpine
        container_name: node-8005
        ports:
            - "8005:8005"
        network_mode: host

        volumes:
            - ./conf/redis-8005.conf:/usr/local/etc/redis/redis.conf
            - ./log:/var/log/redis
            - ./data:/data/redis
        command: sh -c "redis-server /usr/local/etc/redis/redis.conf"



