#!/bin/bash
#2.拉回来
git pull
#33.添加和推上去
git add .  #添加当前目录下的所有文件和子目录
git commit -m  "`date`"  #"dbbak and cutnglog"
git push  origin master 
#git push 

#有时记得要删除
# 尚未暂存以备提交的变更：
#   （使用 "git add/rm <file>..." 更新要提交的内容）
#   （使用 "git checkout -- <file>..." 丢弃工作区的改动）
#   删除：      document/plan
#   删除：      document/plan~

